version: "3"

networks:
  monitoring:
    driver: bridge

volumes: 
  grafana-storage: 
    external: true 

services:
  prometheus: 
    container_name: "prometheus"
    image: "prom/prometheus"
    restart: unless-stopped
    expose:
      - "9090"
    volumes: 
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring 

  grafana:
    container_name: "grafana"
    image: "grafana/grafana-oss"  
    restart: unless-stopped
    expose:
      - "3000"
    volumes: 
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring 

       
  caddy:
    image: arm64v8/caddy
    container_name: caddy 
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9090:9090" 
    volumes:
      - ./caddy:/etc/caddy
    networks:
      - monitoring 
